---
title: "Data Final Project"
author: "MarvinB"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Texas Wide Open
DATA from https://www.kaggle.com/datasets/wumanandpat/irs-migration-data-1992-to-2020
by Patrick O'Connor

```{r}
install.packages("ggforce")
library(tidyverse)
library(ggplot2)
library(ggforce)

irs_SOI_state_migraion_data <- read.csv("irs_SOI_state_migraion_data.csv")

head(irs_SOI_state_migraion_data)
```


```{r}
#table of people migrating from somewhere other than texas
TXdata <- irs_SOI_state_migraion_data %>% filter(Y1_STATE_ABBR != "TX" & Y2_STATE_ABBR == "TX") %>% select(Y1, NUM_EXEMPTIONS, AGI, Y1_STATE_NAME)
head(TXdata)

#change year to factor

#only people migrating from California to Texas
CATXdata <- irs_SOI_state_migraion_data %>% filter(Y1_STATE_ABBR == "CA" & Y2_STATE_ABBR == "TX")
head(CATXdata)

```

# total number of individuals migrating to TX
```{r}

CATXdata <- CATXdata %>% select(Y1, Californians = NUM_EXEMPTIONS, AGI, NUM_RETURNS)

```

```{r}
#Californians Moving to Texas per Year with AGI
head(CATXdata)

#plot of CA people migrating to texas, per year
ggplot(CATXdata, aes(Y1, Californians)) + geom_point() + geom_line()

#Assuming AGI divided by NUM_RETURNS * 1000= household income
CATXdata <- CATXdata %>% mutate(Average_Household_Income = (AGI / NUM_RETURNS)*1000)

AHIdata <- CATXdata %>% select(Y1, Average_Household_Income)

head(AHIdata)

ggplot(AHIdata, aes(x = Y1, y = Average_Household_Income)) + geom_col()
#write.csv(AHIdata, "AHIandCPIdata.csv")

#CPi data listed form
CPI = c(140.317, 144.458, 148.225, 152.383, 156.850, 160.517, 163.008, 166.575, 172.200, 177.067, 179.875, 183.958, 188.883, 195.292, 201.592, 207.342, 215.303, 214.537, 218.056, 224.939, 229.594, 232.957, 236.736, 237.017, 240.011, 245.120, 251.107, 255.657, 258.811 )

#add CPI to AHIdata
AHIdata <- cbind(AHIdata, CPI) 


#inflation rate in 2020 compared to 2022 = 
# [(CPI for 2022 - CPI for 2020 ) / (CPI for 2020)] x 100%

AHIdata <- AHIdata %>% mutate(AHIdata, inflation2022correction = ((292.655 - CPI)/CPI))


#income in 2020 (compared to 2022 dollars) = 
#(income in 2020) / (inflation rate in 2020 compared to 2022)

AHIdata <- AHIdata %>% mutate(Adjusted_in_2022dollars = Average_Household_Income*(1+inflation2022correction))

#Median Household Income (2022 dollars, I believe!) from https://fred.stlouisfed.org/series/MEHOINUSCAA646N
MHI = c(34900, 34070, 35330, 37010, 38810, 39690, 40930, 43630, 46820, 47260, 47440, 49300, 49220, 51760, 55320, 55730, 57010, 56130, 54280, 53370, 57020, 60790, 60490, 63640, 66640, 70040, 70490, 78110, 77650)

AHIdata <- cbind(AHIdata, MHI)

ggplot(AHIdata, aes(x = Y1, y = Adjusted_in_2022dollars)) + geom_line(aes(y=Adjusted_in_2022dollars)) + geom_line(aes(y=MHI))

#plot of household income data adjusted for inflation (2022 dollars)
ggplot(AHIdata, aes(x = Y1, y = Adjusted_in_2022dollars))  + geom_col(aes(y = Adjusted_in_2022dollars)) + geom_line(aes(y =Average_Household_Income, color = "red"))

#COMPAHIdata <- data.frame(both = c(Average_Household_Income, Adjusted_in_2022dollars ))

#insert average household income in california


```


```{r}
#table of ALL people migrating to Texas per year
cumTXdata <- TXdata %>% group_by(Y1) %>% summarise(Total_Migration = sum(NUM_EXEMPTIONS))

head(cumTXdata)

#plot of ALL people migrating to Texas per year
ggplot(TXdata %>% group_by(Y1) %>% summarise(INDIVIDUALS = sum(NUM_EXEMPTIONS)), aes(Y1, y = INDIVIDUALS)) + geom_area()


#Combine CATX data with cumTXdata

cumTXdata <- inner_join(cumTXdata, CATXdata, by = join_by(Y1))

head(cumTXdata)


ggplot(cumTXdata, aes(Y1, y = Total_Migration)) + geom_area() + geom_area(aes(Y1, Californians, fill = Californians))
```

```{r}
#percent of migration Californians over Total Migrants
cumTXdata <- cumTXdata %>% mutate(Percent_Migration = (Californians / Total_Migration)*100)
head(cumTXdata)

ggplot(cumTXdata, aes(Y1, Percent_Migration)) + geom_area() + theme_classic()
```


```{r}
TXvTotalData <- TXdata %>% group_by(Y1) %>% summarise (TotalMigration = sum(NUM_EXEMPTIONS))
p <- TXdata %>% filter(Y1_STATE_NAME == "CALIFORNIA")
TXvTotalData <- right_join(TXvTotalData,p, join_by(Y1))
TXvTotalData

ggplot(TXvTotalData, aes(x = Y1,  y = TotalMigration)) + geom_line()
```


# California to Texas Data

```{r}
ggplot(TXdata, aes(Y1, NUM_EXEMPTIONS)) + geom_point() + geom_line()
```

```{r}

```

