---
title: "Data Final Project"
author: "MarvinB"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Texas Wide Open
DATA from https://www.kaggle.com/datasets/wumanandpat/irs-migration-data-1992-to-2020
by Patrick O'Connor

```{r}
library(tidyverse)
library(ggplot2)

irs_SOI_state_migraion_data <- read.csv("irs_SOI_state_migraion_data.csv")

head(irs_SOI_state_migraion_data)
```


```{r}
#table of people migrating from somewhere other than texas
TXdata <- irs_SOI_state_migraion_data %>% filter(Y1_STATE_ABBR != "TX" & Y2_STATE_ABBR == "TX") %>% select(Y1, NUM_EXEMPTIONS, AGI, Y1_STATE_NAME)
head(TXdata)

#change year to factor

#only people migrating from California to Texas
CATXdata <- irs_SOI_state_migraion_data %>% filter(Y1_STATE_ABBR == "CA" & Y2_STATE_ABBR == "TX")
head(CATXdata)

```

# total number of individuals migrating to TX
```{r}

CATXdata <- CATXdata %>% select(Y1, Californians = NUM_EXEMPTIONS, AGI, NUM_RETURNS)

```

```{r}
#Californians Moving to Texas per Year with AGI
head(CATXdata)

#plot of CA people migrating to texas, per year
ggplot(CATXdata, aes(Y1, Californians)) + geom_point() + geom_line()

#Assuming AGI divided by NUM_RETURNS * 1000= household income
CATXdata <- CATXdata %>% mutate(Average_Household_Income = (AGI / NUM_RETURNS)*1000)

AHIdata <- CATXdata %>% select(Y1, Average_Household_Income)

head(AHIdata)

ggplot(AHIdata, aes(x = Y1, y = Average_Household_Income)) + geom_col()

#ggplot(CATXdata, aes(x= Y1, y = Average_Household_Income)) + geom_point() + geom_line()
```


```{r}
#table of ALL people migrating to Texas per year
cumTXdata <- TXdata %>% group_by(Y1) %>% summarise(Total_Migration = sum(NUM_EXEMPTIONS))

head(cumTXdata)

#plot of ALL people migrating to Texas per year
ggplot(TXdata %>% group_by(Y1) %>% summarise(INDIVIDUALS = sum(NUM_EXEMPTIONS)), aes(Y1, y = INDIVIDUALS)) + geom_area()


#Combine CATX data with cumTXdata

cumTXdata <- inner_join(cumTXdata, CATXdata, by = join_by(Y1))

head(cumTXdata)


ggplot(cumTXdata, aes(Y1, y = Total_Migration)) + geom_area() + geom_area(aes(Y1, Californians, fill = Californians))
```

```{r}
#percent of migration Californians over Total Migrants
cumTXdata <- cumTXdata %>% mutate(Percent_Migration = (Californians / Total_Migration)*100)
head(cumTXdata)

ggplot(cumTXdata, aes(Y1, Percent_Migration)) + geom_area() + theme_classic()
```


```{r}
TXvTotalData <- TXdata %>% group_by(Y1) %>% summarise (TotalMigration = sum(NUM_EXEMPTIONS))
p <- TXdata %>% filter(Y1_STATE_NAME == "CALIFORNIA")
TXvTotalData <- right_join(TXvTotalData,p, join_by(Y1))
TXvTotalData

ggplot(TXvTotalData, aes(x = Y1,  y = TotalMigration)) + geom_line()
```


# California to Texas Data

```{r}
ggplot(TXdata, aes(Y1, NUM_EXEMPTIONS)) + geom_point() + geom_line()
```

```{r}

```

